// Design tokens and component CSS for the create-workflow gateway UI.
// This intentionally mirrors multi's shipped custom UI vocabulary: Inter,
// small dense controls, light-by-default surfaces, soft borders/shadows, glass
// top bars, and color used only for brand/status.
import { workflowUiStyles } from "smithers-orchestrator/gateway-ui";

export const themeCss = [
  workflowUiStyles,
  ":root { color-scheme:light; font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;" +
    " --bg:#ffffff; --text:#0a0a0a; --text-muted:#525252; --text-faint:#6f6f6f; --text-placeholder:#767676;" +
    " --surface:#ffffff; --surface-glass:rgba(255,255,255,0.72); --surface-glass-strong:rgba(255,255,255,0.85);" +
    " --border:rgba(10,10,10,0.08); --border-strong:rgba(10,10,10,0.14); --border-solid:#ededed;" +
    " --hover:#f4f4f4; --hover-subtle:rgba(10,10,10,0.03); --inverse-bg:#0a0a0a; --inverse-text:#ffffff;" +
    " --code-bg:#0a0a0a; --code-text:#f4f4f4; --inline-code-bg:rgba(10,10,10,0.07);" +
    " --brand:#6d56d8; --success:#087461; --danger:#c5343f; --warning:#955600; --shadow-rgb:10 10 10;" +
    " --graph-bg:#fafbfc; --graph-border:#eef0f3; --graph-dots:#e2e7ef;" +
    " --node-bg:#ffffff; --node-border:#d7e0eb; --node-title:#182230; --node-muted:#607087; --node-shadow:rgb(30 42 60 / 10%);" +
    " --panel:var(--surface); --card:var(--surface); --line:var(--border-solid); --muted:var(--text-muted);" +
    " --ok:var(--success); --warn:var(--warning); --bad:var(--danger); --blue:var(--brand); }",
  "@media (prefers-color-scheme: dark) { :root:not([data-theme='light']) { color-scheme:dark;" +
    " --bg:#0b0b0d; --text:#f4f4f5; --text-muted:#a1a1aa; --text-faint:#b0b0b8; --text-placeholder:#83838d;" +
    " --surface:#18181b; --surface-glass:rgba(24,24,27,0.72); --surface-glass-strong:rgba(24,24,27,0.85);" +
    " --border:rgba(255,255,255,0.1); --border-strong:rgba(255,255,255,0.18); --border-solid:#2a2a2e;" +
    " --hover:#26262b; --hover-subtle:rgba(255,255,255,0.05); --inverse-bg:#f4f4f5; --inverse-text:#0a0a0a;" +
    " --code-bg:#09090b; --code-text:#e4e4e7; --inline-code-bg:rgba(255,255,255,0.1);" +
    " --brand:#8b78e6; --success:#2ec9a8; --danger:#f2555a; --warning:#e0a23a; --shadow-rgb:0 0 0;" +
    " --graph-bg:#0e0e11; --graph-border:#1f1f24; --graph-dots:#2a2a2e;" +
    " --node-bg:#18181b; --node-border:#2a2a2e; --node-title:#f4f4f5; --node-muted:#9a9aa6; --node-shadow:rgb(0 0 0 / 45%); } }",
  ":root[data-theme='dark'] { color-scheme:dark;" +
    " --bg:#0b0b0d; --text:#f4f4f5; --text-muted:#a1a1aa; --text-faint:#b0b0b8; --text-placeholder:#83838d;" +
    " --surface:#18181b; --surface-glass:rgba(24,24,27,0.72); --surface-glass-strong:rgba(24,24,27,0.85);" +
    " --border:rgba(255,255,255,0.1); --border-strong:rgba(255,255,255,0.18); --border-solid:#2a2a2e;" +
    " --hover:#26262b; --hover-subtle:rgba(255,255,255,0.05); --inverse-bg:#f4f4f5; --inverse-text:#0a0a0a;" +
    " --code-bg:#09090b; --code-text:#e4e4e7; --inline-code-bg:rgba(255,255,255,0.1);" +
    " --brand:#8b78e6; --success:#2ec9a8; --danger:#f2555a; --warning:#e0a23a; --shadow-rgb:0 0 0;" +
    " --graph-bg:#0e0e11; --graph-border:#1f1f24; --graph-dots:#2a2a2e;" +
    " --node-bg:#18181b; --node-border:#2a2a2e; --node-title:#f4f4f5; --node-muted:#9a9aa6; --node-shadow:rgb(0 0 0 / 45%); }",
  "* { box-sizing:border-box; }",
  "body { min-width:320px; min-height:100vh; margin:0; background:var(--bg); color:var(--text); font-size:13px; font-synthesis:none; text-rendering:optimizeLegibility; -webkit-font-smoothing:antialiased; -moz-osx-font-smoothing:grayscale; }",
  "button,input,textarea,select { font:inherit; }",
  "button { color:inherit; }",
  "h1,h2,h3,p { margin:0; }",
  "h1 { color:var(--text); font-size:15px; font-weight:650; letter-spacing:0; }",
  "h2 { color:var(--text); font-size:14px; font-weight:700; letter-spacing:0; }",
  "h3 { color:var(--text); font-size:12.5px; font-weight:700; letter-spacing:0; }",
  "p { color:var(--muted); line-height:1.45; }",
  "code { font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; }",
  ".shell { height:100vh; display:flex; flex-direction:column; background:var(--bg); color:var(--text); }",
  ".shell > .content { flex:1 1 auto; min-height:0; }",
  ".shell > .top,.shell > .tabbar,.shell > .error-strip { flex:none; }",
  ".error-strip { display:flex; flex-wrap:wrap; align-items:baseline; gap:6px 14px; padding:8px 18px; border-bottom:1px solid color-mix(in srgb,var(--bad) 35%,var(--border)); background:color-mix(in srgb,var(--bad) 8%,var(--surface)); color:var(--bad); font-size:12px; }",
  ".error-strip span { min-width:0; overflow-wrap:anywhere; }",
  ".cmd { display:flex; align-items:center; gap:10px; }",
  ".cmd-label { flex:none; width:220px; color:var(--muted); font-size:11px; }",
  ".cmd-text { flex:1 1 auto; min-width:0; overflow-x:auto; padding:6px 10px; border:1px solid var(--border); border-radius:8px; background:var(--inline-code-bg); font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; font-size:12px; white-space:nowrap; }",
  ".cmd .button { flex:none; min-height:28px; padding:0 10px; font-size:12px; }",
  ".result-graph { min-height:200px; height:220px; }",
  ".tab .badge { min-height:16px; padding:0 6px; font-size:9px; }",
  "@media (max-width: 640px) { .cmd { flex-wrap:wrap; } .cmd-label { width:100%; } }",
  ".top { display:flex; align-items:center; justify-content:space-between; gap:16px; padding:12px 18px; border-bottom:1px solid var(--border); background:var(--surface-glass-strong); -webkit-backdrop-filter:blur(18px) saturate(180%); backdrop-filter:blur(18px) saturate(180%); }",
  ".title { display:flex; align-items:center; gap:10px; min-width:0; }",
  ".title h1 { flex:none; }",
  ".actions { display:flex; align-items:center; justify-content:flex-end; gap:8px; min-width:0; flex:1 1 auto; }",
  ".prompt-input { width:min(38vw,420px); min-width:220px; }",
  ".run-select { width:150px; }",
  ".input,.run-select,textarea.input { min-height:32px; border:1px solid var(--line); border-radius:6px; background:var(--panel); color:var(--text); padding:0 10px; outline:none; }",
  "textarea.input { padding:10px 12px; min-height:96px; resize:vertical; line-height:1.45; }",
  ".input::placeholder,textarea.input::placeholder { color:var(--text-placeholder); }",
  ".input:focus-visible,.run-select:focus-visible,textarea.input:focus-visible { border-color:color-mix(in srgb,var(--brand) 45%,var(--line)); box-shadow:0 0 0 3px color-mix(in srgb,var(--brand) 18%,transparent); }",
  ".button { min-height:32px; display:inline-flex; align-items:center; justify-content:center; gap:6px; padding:0 12px; border:1px solid var(--line); border-radius:6px; background:var(--panel); color:var(--text); text-decoration:none; cursor:pointer; white-space:nowrap; }",
  ".button:hover { background:var(--hover); }",
  ".button:focus-visible { outline:none; box-shadow:0 0 0 3px color-mix(in srgb,var(--brand) 22%,transparent); }",
  ".button:disabled { cursor:not-allowed; opacity:.45; }",
  ".button.primary { border-color:color-mix(in srgb,var(--brand) 40%,transparent); background:color-mix(in srgb,var(--brand) 10%,var(--surface)); color:var(--brand); font-weight:650; }",
  ".button.primary:hover { background:color-mix(in srgb,var(--brand) 16%,var(--surface)); }",
  ".button.ok { border-color:color-mix(in srgb,var(--ok) 45%,transparent); background:color-mix(in srgb,var(--ok) 10%,var(--surface)); color:var(--ok); font-weight:650; }",
  ".button.danger { border-color:color-mix(in srgb,var(--bad) 38%,transparent); color:var(--bad); }",
  ".button.danger:hover { background:color-mix(in srgb,var(--bad) 8%,var(--surface)); }",
  ".pill,.badge { display:inline-flex; align-items:center; gap:6px; min-height:22px; max-width:220px; padding:1px 10px; border:1px solid var(--border); border-radius:999px; color:var(--text-muted); font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; font-size:11px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }",
  ".pill { border-color:color-mix(in srgb,var(--brand) 22%,transparent); background:color-mix(in srgb,var(--brand) 14%,transparent); color:var(--brand); }",
  ".badge { font-family:inherit; font-weight:650; text-transform:uppercase; }",
  ".badge.ok { color:var(--ok); border-color:color-mix(in srgb,var(--ok),transparent 45%); }",
  ".badge.warn,.badge.run { color:var(--warn); border-color:color-mix(in srgb,var(--warn),transparent 45%); }",
  ".badge.bad { color:var(--bad); border-color:color-mix(in srgb,var(--bad),transparent 45%); }",
  ".badge.info { color:var(--brand); border-color:color-mix(in srgb,var(--brand),transparent 45%); }",
  ".live { display:inline-flex; align-items:center; gap:6px; color:var(--muted); font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; font-size:11px; white-space:nowrap; }",
  ".live-dot { width:7px; height:7px; border-radius:50%; background:var(--text-faint); }",
  ".live.on .live-dot,.tab-glyph.is-active { background:var(--ok); animation:cw-pulse 1.6s infinite; }",
  "@keyframes cw-pulse { 0%{box-shadow:0 0 0 0 color-mix(in srgb,var(--ok) 45%,transparent);} 70%{box-shadow:0 0 0 6px transparent;} 100%{box-shadow:0 0 0 0 transparent;} }",
  ".tabbar { display:flex; align-items:center; gap:6px; padding:8px 14px; border-bottom:1px solid var(--border); background:var(--surface); overflow-x:auto; }",
  ".tab { min-height:30px; display:inline-flex; align-items:center; gap:7px; padding:0 12px; border:1px solid transparent; border-radius:6px; background:transparent; color:var(--muted); font-weight:650; cursor:pointer; white-space:nowrap; }",
  ".tab:hover { color:var(--text); }",
  ".tab:focus-visible { outline:none; box-shadow:0 0 0 3px color-mix(in srgb,var(--brand) 18%,transparent); }",
  ".tab.is-active { background:color-mix(in srgb,var(--brand) 12%,transparent); border-color:color-mix(in srgb,var(--brand) 30%,transparent); color:var(--brand); }",
  ".tab-glyph { width:9px; height:9px; border-radius:50%; display:inline-flex; align-items:center; justify-content:center; color:var(--text-faint); font-size:10px; line-height:1; }",
  ".tab-glyph.is-done { color:var(--ok); }",
  ".tab-glyph.is-failed { color:var(--bad); }",
  ".tab-glyph.is-pending { color:var(--text-faint); opacity:.55; }",
  ".tab-glyph.is-active { color:transparent; }",
  ".content { min-height:0; overflow:hidden; display:grid; grid-template-rows:minmax(0,1fr) auto; background:var(--bg); }",
  ".content > [hidden] { display:none; }",
  ".pane { min-height:0; overflow:auto; padding:16px 18px; display:grid; align-content:start; gap:14px; }",
  ".pane-fill { overflow:hidden; align-content:stretch; grid-template-rows:auto minmax(0,1fr); }",
  ".pane-head { display:flex; align-items:flex-start; justify-content:space-between; gap:16px; }",
  ".pane-title { min-width:0; display:grid; gap:4px; }",
  ".eyebrow { display:block; color:var(--muted); font-size:10px; text-transform:uppercase; letter-spacing:.06em; }",
  ".muted { color:var(--muted); }",
  ".mono { font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; }",
  ".stack { display:grid; gap:10px; align-content:start; }",
  ".soft-grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); gap:10px; align-items:start; }",
  ".card { display:grid; gap:9px; padding:14px; border:1px solid var(--border); border-radius:14px; background:var(--surface); box-shadow:0 1px 2px rgb(var(--shadow-rgb) / 0.04), 0 8px 24px rgb(var(--shadow-rgb) / 0.06); }",
  ".card.subtle { box-shadow:none; background:color-mix(in srgb,var(--surface) 94%,var(--hover)); }",
  ".card-head { display:flex; align-items:center; justify-content:space-between; gap:10px; }",
  ".chips { display:flex; flex-wrap:wrap; gap:6px; }",
  ".chip { min-height:22px; display:inline-flex; align-items:center; max-width:100%; padding:1px 9px; border:1px solid var(--border); border-radius:999px; background:var(--surface); color:var(--muted); font-size:11px; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }",
  ".chip.brand { color:var(--brand); border-color:color-mix(in srgb,var(--brand) 32%,transparent); background:color-mix(in srgb,var(--brand) 7%,var(--surface)); }",
  ".resource { display:grid; gap:6px; min-width:0; padding:10px 11px; border:1px solid var(--border); border-radius:10px; background:var(--surface); }",
  ".resource strong { min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-size:12px; }",
  ".resource p { font-size:12px; }",
  ".editor-frame { min-height:0; overflow:hidden; border:1px solid var(--border); border-radius:10px; background:var(--surface); }",
  ".editor-frame.compact .crepe-host { max-height:220px; }",
  ".editor-frame.readonly .crepe-host { min-height:220px; }",
  ".crepe-host { min-height:0; overflow:auto; }",
  ".crepe-host .milkdown { height:100%; background:var(--surface); color:var(--text); }",
  ".crepe-host .milkdown .ProseMirror { padding:18px 22px; font-size:13px; line-height:1.55; }",
  ".design-pane { min-height:0; display:grid; grid-template-rows:minmax(320px,1fr) auto; gap:12px; }",
  ".graph-wrap { min-height:320px; height:100%; overflow:hidden; border:1px solid var(--graph-border); border-radius:14px; background:var(--graph-bg); }",
  ".graph-wrap .react-flow { height:100%; background:var(--graph-bg); }",
  ".smithers-node { display:grid; gap:6px; align-content:center; width:220px; min-height:96px; padding:14px 16px; border:1px solid var(--node-border); border-left-width:5px; border-radius:7px; background:var(--node-bg); box-shadow:0 8px 18px var(--node-shadow); }",
  ".smithers-node.is-running { box-shadow:0 0 0 2px color-mix(in srgb,var(--brand) 55%,transparent), 0 8px 18px var(--node-shadow); }",
  ".smithers-node.is-done { border-color:color-mix(in srgb,var(--ok) 45%,var(--node-border)); }",
  ".smithers-node.is-failed { border-color:color-mix(in srgb,var(--bad) 55%,var(--node-border)); }",
  ".smithers-node-agent { border-left-color:var(--success); }",
  ".smithers-node-approval { border-left-color:#bf5b16; }",
  ".smithers-node-compute { border-left-color:#356fd2; }",
  ".smithers-node-loop { border-left-color:#6d56d8; }",
  ".smithers-node-branch,.smithers-node-signal { border-left-color:#61738a; }",
  ".smithers-node-merge { border-left-color:#2670a9; }",
  ".smithers-node-human { border-left-color:#a34d9f; }",
  ".node-kicker { display:flex; align-items:center; gap:6px; color:var(--node-muted); font-size:11px; font-weight:800; text-transform:uppercase; }",
  ".node-title { overflow:hidden; color:var(--node-title); font-size:15px; font-weight:800; text-overflow:ellipsis; white-space:nowrap; }",
  ".node-output { overflow:hidden; color:var(--node-muted); font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; font-size:12px; text-overflow:ellipsis; white-space:nowrap; }",
  ".node-dot { width:7px; height:7px; border-radius:50%; background:var(--node-muted); }",
  ".node-dot.run { background:var(--brand); } .node-dot.ok { background:var(--ok); } .node-dot.bad { background:var(--bad); } .node-dot.warn { background:var(--warn); }",
  ".gate { display:grid; gap:12px; max-width:860px; padding:16px; border:1px solid color-mix(in srgb,var(--brand) 35%,var(--border)); border-radius:14px; background:color-mix(in srgb,var(--brand) 6%,var(--surface)); box-shadow:0 1px 2px rgb(var(--shadow-rgb) / 0.04), 0 8px 24px rgb(var(--shadow-rgb) / 0.06); }",
  ".gate.done { border-color:color-mix(in srgb,var(--ok) 40%,var(--border)); background:color-mix(in srgb,var(--ok) 6%,var(--surface)); }",
  ".gate.denied { border-color:color-mix(in srgb,var(--bad) 40%,var(--border)); background:color-mix(in srgb,var(--bad) 6%,var(--surface)); }",
  ".gate-actions { display:flex; align-items:center; gap:8px; flex-wrap:wrap; }",
  ".files { list-style:none; margin:0; padding:0; display:grid; gap:0; }",
  ".files li { display:flex; align-items:center; justify-content:space-between; gap:12px; padding:7px 0; border-bottom:1px solid var(--border); font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; font-size:12px; }",
  ".files li:last-child { border-bottom:0; }",
  ".files .path { min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }",
  ".files .kind { flex:none; color:var(--muted); font-size:10px; text-transform:uppercase; letter-spacing:.04em; }",
  ".result { display:grid; grid-template-columns:max-content minmax(0,1fr); gap:7px 16px; align-items:baseline; }",
  ".result .label { color:var(--muted); font-size:10px; text-transform:uppercase; letter-spacing:.05em; }",
  ".result .val { min-width:0; overflow-wrap:anywhere; font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; font-size:12px; }",
  ".code { display:block; max-height:260px; overflow:auto; padding:10px; border:1px solid var(--border); border-radius:10px; background:var(--code-bg); color:var(--code-text); font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; font-size:11px; line-height:1.55; white-space:pre-wrap; }",
  ".pending-hint { display:grid; place-items:center; min-height:220px; padding:28px; border:1px dashed var(--border-strong); border-radius:12px; color:var(--muted); text-align:center; }",
  ".launch { display:grid; place-items:center; min-height:100%; padding:28px 18px; }",
  ".launch-card { width:min(100%,640px); display:grid; gap:13px; padding:16px; border:1px solid var(--border); border-radius:14px; background:var(--surface); box-shadow:0 1px 2px rgb(var(--shadow-rgb) / 0.04), 0 12px 34px rgb(var(--shadow-rgb) / 0.08); }",
  ".launch-row { display:flex; align-items:center; justify-content:space-between; gap:12px; flex-wrap:wrap; }",
  ".check { display:inline-flex; align-items:center; gap:6px; color:var(--muted); cursor:pointer; user-select:none; font-size:12px; }",
  ".activity { border-top:1px solid var(--border); background:var(--surface); }",
  ".activity-head { width:100%; min-height:36px; display:flex; align-items:center; gap:8px; padding:0 14px; border:0; background:var(--surface); color:var(--muted); cursor:pointer; text-align:left; }",
  ".activity-head:hover { background:var(--hover-subtle); }",
  ".activity-head .grow { flex:1; }",
  ".livelog { max-height:176px; overflow:auto; background:var(--code-bg); border-top:1px solid var(--border); padding:8px 10px; font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; font-size:11px; line-height:1.55; }",
  ".livelog-line { display:flex; align-items:baseline; gap:8px; padding:1px 0; white-space:nowrap; }",
  ".livelog-seq { flex:none; width:34px; color:var(--text-faint); text-align:right; opacity:.72; }",
  ".livelog-event { flex:none; font-weight:650; }",
  ".livelog-event.ok { color:var(--ok); } .livelog-event.bad { color:var(--bad); } .livelog-event.warn { color:var(--warn); } .livelog-event.info { color:var(--brand); } .livelog-event.muted { color:var(--text-faint); }",
  ".livelog-node { flex:none; color:var(--warn); }",
  ".livelog-detail { min-width:0; overflow:hidden; color:var(--code-text); text-overflow:ellipsis; }",
  ".empty { padding:18px; color:var(--muted); text-align:center; }",
  "@media (max-width: 900px) { .top { align-items:flex-start; flex-direction:column; } .actions { width:100%; justify-content:flex-start; } .prompt-input { flex:1 1 260px; width:auto; } .run-select { width:140px; } .pane-head { display:grid; } .design-pane { grid-template-rows:minmax(300px,46vh) auto; } }",
  "@media (max-width: 640px) { .top { padding:10px 12px; } .tabbar { padding:8px 10px; } .pane { padding:12px; } .title { flex-wrap:wrap; } .actions { gap:6px; } .prompt-input,.run-select { flex:1 1 100%; width:100%; } .button { flex:0 0 auto; } .soft-grid { grid-template-columns:1fr; } .result { grid-template-columns:1fr; gap:3px 0; } }",
].join("\n");
