// Original TypeScript reference oracle; rebuild apps/mcp-server/dist before regenerating.
import {parseAlsXml,modelFromAlsXml,extractAlsMidi,lintAlsModel} from '../../../../apps/mcp-server/dist/src/als.js';
import {semanticProjectName,canonicalSemanticJson} from '../../../../apps/mcp-server/dist/src/project-semantic.js';
import {writeFileSync} from 'node:fs';
const result = fn => {try{return {ok:fn()}}catch(e){return {error:e.message}}};
const xmlCases=['',' ','<Ableton/>','<Ableton a = \'one &amp; two\'/>','<Ableton><!-- <MidiTrack/> --><LiveSet><![CDATA[<MidiTrack/>]]></LiveSet></Ableton>', '<?xml version="1.0"?><Ableton/>','<!-- before --><?xml version="1"?><Ableton/>','<Ableton/><Extra/>','<Ableton>outside','outside<Ableton/>','<Ableton><X></Ableton>','<Ableton><X></X unexpected="1"></Ableton>','<Ableton/ >garbage','<Ableton><!-- unclosed</Ableton>','<Ableton><X a="&unknown;"/></Ableton>','<Ableton/><Unclosed>','<Ableton><![CDATA[unclosed</Ableton>','<Ableton><X a="1" a="2"/></Ableton>','<Ableton><X a=unquoted/></Ableton>','<Ableton><!-- a--b --></Ableton>','<Ableton><![CDATA[  ]]></Ableton>','<!DOCTYPE x><Ableton/>','<Ableton><!-- <!entity x> --></Ableton>','<Ableton>&amp;lt;&#x1f600;&#0;&#xD800;&#1114112;</Ableton>'];
for(const entity of ['amp','lt','gt','quot','apos','#10','#x1F600','#xD800','#1114112','#x110000','#xFFFFFFFF','#999999999999999999999999999999999999','bogus','#x','#-1','#X41']) xmlCases.push(`<Ableton a="&${entity};">&${entity};</Ableton>`);
for(const space of [' ','\t','\n','\u00a0','\u0085','\ufeff','\u2003'])xmlCases.push(`<Ableton${space}a${space}=${space}"1"${space}/>`);
for(const n of [63,64,65])xmlCases.push('<x>'.repeat(n)+'</x>'.repeat(n));
for(const n of [64,65])xmlCases.push('<Ableton '+Array.from({length:n},(_,i)=>`a${i}="x"`).join(' ')+'/>');
const envelope = body=>`<Ableton Creator="Live 12" MajorVersion="5"><LiveSet>${body}</LiveSet></Ableton>`;
const clip=(attrs,children='')=>`<MidiClip ${attrs}><Name Value="Phrase"/>${children}</MidiClip>`;
const track=body=>`<MidiTrack><Name><EffectiveName Value="Drums"/></Name><Color Value="4"/><DeviceChain>${body}</DeviceChain></MidiTrack>`;
const note=(attrs,key='60')=>`<KeyTrack MidiKey="${key}"><MidiNoteEvent ${attrs}/></KeyTrack>`;
const cases=[];
const add=(label,xml)=>{const model=result(()=>modelFromAlsXml(parseAlsXml(xml),'Fixture'));cases.push({label,xml,model,...('ok'in model?{midi:extractAlsMidi(model.ok),strictMidi:extractAlsMidi(model.ok,'strict'),lint:lintAlsModel(model.ok)}:{})});};
add('empty',envelope(''));
add('wrong root','<LiveSet/>');
add('full',envelope(`<Tracks>${track(`<Mixer><Volume><Manual Value="0.8"/></Volume><Pan Value="-0.25"/></Mixer><Devices><PluginDevice><UserName Value="Synth"/></PluginDevice></Devices><ClipSlots><ClipSlot/><ClipSlot><ClipSlot>${clip('Time="0" Length="4"',note('Time="0" Duration="1" Velocity="99.5"'))}</ClipSlot></ClipSlot></ClipSlots><ArrangerAutomation><Events>${clip('Time="32" Length="4"')}</Events></ArrangerAutomation>`)}${track('')}</Tracks><Scenes><Scene><Name Value="Scene"/><Tempo Value="97"/></Scene></Scenes><Locators><Locator Time="16"><Name Value="Verse"/></Locator><Locator><Time Value="0"/><Name Value="Intro"/></Locator></Locators><MasterTrack><Mixer><Tempo><Manual Value="120"/></Tempo></Mixer></MasterTrack>`));
for(const attrs of ['','Time="8"','Time="8" Length="-1"','Time="8" Length="0"','CurrentEnd="12"','Length="0b100"','Time="NaN" Length="4"']) add('timing '+attrs,envelope(`<Tracks>${track(`<Arrangement>${clip(attrs,'<CurrentStart Value="8"/><CurrentEnd Value="12"/><Loop LoopStart="1" LoopEnd="3"><LoopOn Value="1"/></Loop><Disabled Value="false"/>')}</Arrangement>`)}</Tracks>`));
for(const pitch of ['60','-1','128','60.5','NaN','','0x3c'])for(const velocity of ['-1','0','1','0.49999999999999994','99.5','128','NaN'])add(`note ${pitch} ${velocity}`,envelope(`<Tracks>${track(`<ClipSlot>${clip('Length="4"',note(`Time="0" Duration="1" Velocity="${velocity}" OffVelocity="127.5" Probability="2" IsEnabled="false" VelocityDeviation="-3"`,pitch))}</ClipSlot>`)}</Tracks>`));
for(const tempo of ['19','20','999','1000','NaN','120'])add(`tempo ${tempo}`,envelope(`<Tempo Value="${tempo}"/><MasterTrack><Mixer><Volume Value="1"/></Mixer></MasterTrack>`));
add('audio',envelope(`<Tracks><AudioTrack><Name><UserName Value="Audio"/></Name><Arrangement><AudioClip Time="32" Length="64" SampleLength="128"><Name Value="Long"/><IsWarped Value="false"/><SampleRef><FileRef><RelativePath Value="Samples/test.wav"/></FileRef></SampleRef><WarpMarker/><WarpMarker/></AudioClip></Arrangement></AudioTrack></Tracks><Locators><Locator Time="16"/></Locators>`));
const names=[];for(const profile of ['strict','collaboration','local'])for(const value of ['Drums','e\u0301','Verse / Chorus',' /Users/name','file:///tmp/x','C:\\a','\\\\server\\file','track:12','10:device:4','Bearer abcdefgh','access_token=x','reusable mutation token','prefix /Users/a','a / b','a /x','x\u0085/y','x\ufeff/y','','😀'.repeat(260),null,12])names.push({profile,value,result:semanticProjectName(profile,'track',value)});
const canonicalCases=[null,true,0,-0,1e21,{'😀':1,'\ue000':2,a:3},'😀'.repeat(2048),'a'.repeat(4097),Object.fromEntries(Array.from({length:65},(_,i)=>['k'+i,i])),{['a'.repeat(129)]:1}];for(const depth of [24,25]){let v=0;for(let i=0;i<depth;i++)v=[v];canonicalCases.push(v);}
writeFileSync(new URL('./als_oracle.json',import.meta.url),JSON.stringify({xml:xmlCases.map(xml=>({xml,result:result(()=>parseAlsXml(xml))})),cases,names,canonical:canonicalCases.map(value=>({value,result:result(()=>canonicalSemanticJson(value))}))},null,2)+'\n');
