import {McpHost} from '../../../../apps/mcp-server/dist/src/host.js';
import {DeterministicLiveSimulator,LIVE_REGISTRY_OPERATIONS} from '../../../../apps/mcp-server/dist/src/live.js';
import {FIXTURE_FILES_DB_BASE64,FIXTURE_PLUGINS_DB_BASE64} from '../../../../apps/mcp-server/dist/test/library-fixtures.js';
import {writeFileSync,readFileSync,mkdtempSync,rmSync,realpathSync,mkdirSync,symlinkSync,truncateSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const names={live_arrangement_automation_read:'liveArrangementAutomationReadAsync',live_take_lane_read:'liveTakeLaneReadAsync',live_comp_read:'liveCompReadAsync',live_warp_marker_read:'liveWarpMarkerReadAsync',live_browser_inspect:'liveBrowserInspectAsync',live_library_search:'liveLibrarySearchAsync'};
const parse=v=>{if(v?.result?.content?.[0]?.type==='text')v.result.content[0].text=JSON.parse(v.result.content[0].text);return v};
const base=new DeterministicLiveSimulator().snapshot();base.tracks[0].clips[0].isAudio=true;
const clip={ref:'arrangement-clip:0:0',objectIdentity:'arr-1',trackRef:'track:track-1',kind:'audio',notes:[],warp:false,takes:[],automation:[],name:'Take',start:4,length:8,isAudio:true};
base.arrangement.clips=[clip];base.arrangementClips=[{trackRef:'track:track-1',clip:structuredClone(clip)}];base.tracks[0].takeLanes[0].clips=[{...clip,ref:'take-lane-clip:0:0:0',objectIdentity:'take-1',warpMarkers:[{beatTime:0,sampleTime:0},{beatTime:4,sampleTime:2}]}];
base.tracks[0].takeLanes.push({ref:'take-lane:track-1:1',objectIdentity:'lane-2',name:'Second',index:1,clips:[]});
const reads={live_arrangement_automation_read:{available:true,exists:true,points:[{time:4,value:.8,discard:true},{time:0,value:.3},{time:4,value:.4}]},live_take_lane_read:{lanes:[{ref:'take-lane:track-1:0',name:'First'},{ref:'take-lane:track-1:1',name:'Second'}]},live_comp_read:{segments:[{laneRef:'take-lane:track-1:1',from:4,to:8},{laneRef:'take-lane:track-1:0',from:0,to:4}]},live_warp_marker_read:{revision:'adapter-revision',markers:[{beatTime:4,sampleTime:2},{beatTime:0,sampleTime:0}]},live_browser_inspect:{id:'instruments/Rack',objectIdentity:'browser-1',name:'Rack',category:'instruments',path:'instruments/Rack',isDevice:true}};
const valid={live_arrangement_automation_read:{clipRef:clip.ref,parameterRef:'parameter:gain-1'},live_take_lane_read:{trackRef:'track:track-1'},live_comp_read:{clipRef:clip.ref},live_warp_marker_read:{clipRef:clip.ref},live_browser_inspect:{itemId:'instruments/Rack'}};
const cases=[];function patch(s,changes=[]){for(const [path,value] of changes){let o=s;for(const k of path.slice(0,-1))o=o[k];if(value===undefined)delete o[path.at(-1)];else o[path.at(-1)]=structuredClone(value);}}
const normalize=v=>{if(Array.isArray(v))return v.map(normalize);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,v])=>[k,k==='deadlineMs'?0:normalize(v)]));return v};
async function run(tool,args,extra={}){const sim=new DeterministicLiveSimulator(),status={...sim.status(),operations:[...LIVE_REGISTRY_OPERATIONS],...extra.status},s=structuredClone(base),calls=[];patch(s,extra.patch);sim.status=()=>structuredClone(status);sim.snapshotAsync=async(c,r)=>{calls.push({kind:'snapshot',context:c??null,request:r??null});if(extra.snapshotFail)throw Error(extra.snapshotFail);return structuredClone(s)};sim.invokeAsync=async(i,c)=>{calls.push({kind:'invoke',invocation:i,context:c??null});if(extra.invokeFail)throw Error(extra.invokeFail);return structuredClone(Object.hasOwn(extra,'read')?extra.read:reads[tool]);};const host=new McpHost(sim),row={tool,args,...extra,calls};try{row.result=parse(await host[names[tool]](1,args));}catch(e){row.error=e.message;}cases.push(normalize(row));return row;}
const bad=[null,[],{},0,1,-1,1.5,false,true,'','x','a'.repeat(257)];
for(const [tool,args] of Object.entries(valid)){await run(tool,args);for(const v of bad)await run(tool,v);await run(tool,{...args,extra:1});for(const k of Object.keys(args)){const omit={...args};delete omit[k];await run(tool,omit);for(const v of bad)await run(tool,{...args,[k]:v});}for(const status of [{connected:false},{capabilities:[]},{operations:[]},{epoch:2},{provenance:'simulator',environment:{liveVersion:"12.4.5",liveEdition:"Suite",os:"macOS",api:"LOM"}}])await run(tool,args,{status});for(const read of bad)await run(tool,args,{read});await run(tool,args,{invokeFail:'request failed'});await run(tool,args,{snapshotFail:'request failed'});if(tool!=='live_browser_inspect'){for(const key of ['limit','cursor'])for(const v of [...bad,128,256,512,513,1025])await run(tool,{...args,[key]:v});const first=await run(tool,{...args,limit:1});const text=first.result.result.content[0].text;const cursor=text.paging?.nextCursor;if(cursor){await run(tool,{...args,limit:1,cursor});await run(tool,{...args,cursor:cursor+'!!'});for(const offset of [-1,0,1,2,3,1.5,'1',null]){const c=JSON.parse(Buffer.from(cursor,'base64url'));c.offset=offset;await run(tool,{...args,cursor:Buffer.from(JSON.stringify(c)).toString('base64url')});}const c=JSON.parse(Buffer.from(cursor,'base64url'));c.revision='stale';await run(tool,{...args,cursor:Buffer.from(JSON.stringify(c)).toString('base64url')});}}
}
for(const path of ['/Users/private/Library/file','C:\\Users\\private','D:/home/private','\\\\server\\file','relative\\file','x:relative',null,1,''])await run('live_browser_inspect',valid.live_browser_inspect,{read:{...reads.live_browser_inspect,path}});
for(const key of ['id','objectIdentity','name','category','isDevice'])for(const value of [null,'',true,0])await run('live_browser_inspect',valid.live_browser_inspect,{read:{...reads.live_browser_inspect,[key]:value}});
for(const tool of ['live_arrangement_automation_read','live_comp_read','live_warp_marker_read'])for(const ref of ['clip:clip-1','take-lane-clip:0:0:0','missing'])await run(tool,{...valid[tool],clipRef:ref});
for(const [tool,key] of [['live_arrangement_automation_read','points'],['live_take_lane_read','lanes'],['live_comp_read','segments'],['live_warp_marker_read','markers']])for(const collection of [[],[null],['bad'],[{}],[null,...reads[tool][key]],[...reads[tool][key],...reads[tool][key]]])await run(tool,valid[tool],{read:{...reads[tool],[key]:collection}});
for(const changes of [ [[['tracks',0,'objectIdentity'],null]], [[['tracks',0,'takeLanes'],[]]], [[['arrangement','clips',0,'objectIdentity'],null]], [[['tracks',0,'clips',0,'objectIdentity'],null]], [[['tracks',0,'clipSlots'],[]]], [[['scenes'],[]]] ])for(const tool of ['live_take_lane_read','live_comp_read','live_warp_marker_read'])await run(tool,valid[tool],{patch:changes});
// Parameter search visits normal parameters, rack macros, nested chains, and drum-pad chains.
const parameter=base.tracks[0].devices[0].parameters[0];const dev={ref:'device:nested',name:'Nested',kind:'rack',parameters:[]};const chain={ref:'chain:c',parentRef:'device:nested',name:'Chain'};const pad={ref:'drum-pad:p',parentRef:'device:nested',index:0,name:'Pad',mute:false};for(const device of [{...dev,macros:[parameter]},{...dev,chains:[{...chain,devices:[{...dev,parameters:[parameter]}]}]},{...dev,drumPads:[{...pad,chains:[{...chain,devices:[{...dev,macros:[parameter]}]}]}]},{...dev,parameters:[]}])await run('live_arrangement_automation_read',valid.live_arrangement_automation_read,{patch:[[['tracks',0,'devices'],[device]]]});
const helpers=[];const helperHost=new McpHost();
function helper(method,arg,extra={}){const snap=structuredClone(base);patch(snap,extra.patch);for(const path of extra.remove??[]){let o=snap;for(const k of path.slice(0,-1))o=o[k];delete o[path.at(-1)];}const row={method,arg,...extra};try{row.result=helperHost[method](...(method==='boundedClipContentDigest'||method==='warpMarkerCollectionRevision'?[arg]:[snap,arg]));}catch(e){row.error=e.message;}helpers.push(row);}
for(const method of ['clipAuthority','arrangementClipAuthority','clipAuthorityDigest'])for(const ref of ['clip:clip-1','arrangement-clip:0:0','take-lane-clip:0:0:0','missing']){helper(method,ref);for(const path of [['tracks',0,'objectIdentity'],['tracks',0,'clips',0,'objectIdentity'],['tracks',0,'takeLanes',0,'objectIdentity'],['tracks',0,'takeLanes',0,'clips',0,'objectIdentity'],['arrangement','clips',0,'objectIdentity']])helper(method,ref,{remove:[path]});}
for(const ref of ['track:track-1','missing'])helper('arrangementCollectionRevision',ref);
for(const arg of [{},{name:'é😀',warpMarkers:[{beatTime:-0,sampleTime:1.25}]},{clipView:{nested:{a:[1,true,null,'x']}}}])helper('boundedClipContentDigest',arg);
for(const arg of [[],[{beatTime:8,sampleTime:4},{beatTime:0,sampleTime:0}],[{beatTime:0}], [{beatTime:1,sampleTime:2},{beatTime:1,sampleTime:3}]])helper('warpMarkerCollectionRevision',arg);
const root=realpathSync(mkdtempSync(join(tmpdir(),'host-library-oracle-')));const db=join(root,'files.db'),plugins=join(root,'plugins.db');writeFileSync(db,Buffer.from(FIXTURE_FILES_DB_BASE64,'base64'));writeFileSync(plugins,Buffer.from(FIXTURE_PLUGINS_DB_BASE64,'base64'));writeFileSync(join(root,'bad.db'),'bad');mkdirSync(join(root,'nested'));symlinkSync(db,join(root,'link.db'));symlinkSync(root,join(root,'link-dir'));writeFileSync(join(root,'large.db'),'');truncateSync(join(root,'large.db'),128*1024*1024+1);
const library=[];const host=new McpHost();function norm(v){if(typeof v==='string')return v.replaceAll(root,'ROOT');if(Array.isArray(v))return v.map(norm);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,v])=>[k,norm(v)]));return v;}
async function lib(args,wal=false){const row={args,wal};if(wal){let bytes=readFileSync(db);bytes[18]=bytes[19]=2;writeFileSync(db,bytes);writeFileSync(db+'-wal','WAL');}try{row.result=parse(await host.liveLibrarySearchAsync(1,args));}catch(e){row.error=e.message;}library.push(norm(row));if(wal){let bytes=readFileSync(db);bytes[18]=bytes[19]=1;writeFileSync(db,bytes);rmSync(db+'-wal');}return row;}
const args={database:db,allowlistRoot:root};await lib(args);for(const v of bad)await lib(v);for(const mode of ['files','plugins','tags',['files'],['plugins'],['tags']]){await lib({...args,pluginsDatabase:plugins,mode,limit:2});for(const sort of ['name','modified','useCount',['name'],['modified']])await lib({...args,pluginsDatabase:plugins,mode,sort,limit:2});}
for(const key of ['database','allowlistRoot','pluginsDatabase','mode','query','tags','kinds','sources','vendors','formats','sort','limit','cursor'])for(const v of bad)await lib({...args,[key]:v});
for(const kinds of [['audio'],[['audio']],[['audio'],'audio'],['device','preset'],[['preset'],['preset']]])await lib({...args,kinds,limit:1});for(const formats of [['vst3'],[['vst3']],[['vst3'],'au']])await lib({...args,pluginsDatabase:plugins,mode:'plugins',formats,limit:1});
for(const v of [{toString:null},[{toString:0}]])for(const key of ['mode','sort'])await lib({...args,[key]:v});
for(const database of [join(root,'missing'),join(root,'bad.db'),join(root,'large.db'),join(root,'nested'),join(root,'link.db')])await lib({...args,database});for(const allowlistRoot of [join(root,'nested'),join(root,'link-dir'),join(root,'missing'),db])await lib({...args,allowlistRoot});await lib({...args,mode:'plugins'});await lib(args,true);
for(const mode of ['files','plugins','tags',['files']]){const first=await lib({...args,mode,pluginsDatabase:plugins,limit:1});const cursor=first.result.result.content[0].text.paging?.nextCursor;if(cursor){await lib({...args,mode,pluginsDatabase:plugins,limit:1,cursor});await lib({...args,mode,pluginsDatabase:plugins,limit:1,cursor:cursor+'!!'});await lib({...args,mode,pluginsDatabase:plugins,limit:1,cursor,query:'Kick'});}}
rmSync(root,{recursive:true,force:true});writeFileSync(new URL('./host_probes_oracle.json',import.meta.url),JSON.stringify({base,reads,cases,library,helpers})+'\n');console.log({cases:cases.length,library:library.length});
