import {McpHost} from '../../../../apps/mcp-server/dist/src/host.js';
import {DeterministicLiveSimulator,LIVE_REGISTRY_OPERATIONS} from '../../../../apps/mcp-server/dist/src/live.js';
import {writeFileSync,readFileSync,mkdtempSync,rmSync,realpathSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {gzipSync} from 'node:zlib';
const methods={live_project_info:'liveProjectInfoAsync',live_project_snapshot_export:'liveProjectSnapshotExportAsync',live_project_snapshot_diff:'liveProjectSnapshotDiff',live_project_backup_preview:'liveProjectBackupPreviewAsync',live_project_backup_apply:'liveProjectBackupApplyAsync',als_read:'alsRead',als_lint:'alsLint',als_diff:'alsDiff'};
const parse=v=>{if(v?.result?.content?.[0]?.type==='text')v.result.content[0].text=JSON.parse(v.result.content[0].text);return v};
const cases=[];const base=new DeterministicLiveSimulator().snapshot();
async function run(tool,args,extra={}){const sim=new DeterministicLiveSimulator(),calls=[];const status=sim.status();status.operations=[...LIVE_REGISTRY_OPERATIONS];Object.assign(status,extra.status??{});sim.status=()=>structuredClone(status);const snapshotAsync=sim.snapshotAsync.bind(sim);sim.snapshotAsync=async(c,r)=>{calls.push({context:c??null,request:r??null});if(extra.fail)throw Error(extra.fail);return snapshotAsync(c,r);};const host=new McpHost(sim);const row={tool,args,...extra,calls};try{row.result=parse(await host[methods[tool]](1,args));}catch(e){row.error=e.message;}cases.push(row);}
const valid={live_project_info:{},live_project_snapshot_export:{},live_project_snapshot_diff:{beforePages:[],afterPages:[]},live_project_backup_preview:{confirmation:'backup',allowedRoot:'/tmp/unused'},live_project_backup_apply:{transactionId:'backup_unknown',confirmation:'apply',idempotencyKey:'test-key'},als_read:{path:'/relative',allowedRoot:''},als_lint:{path:'relative',allowedRoot:'/tmp'},als_diff:{before:{pages:[]},after:{pages:[]}}};
const bad=[null,[],0,1,-1,1.5,false,true,'','x'];
for(const [tool,args] of Object.entries(valid)){await run(tool,args);for(const v of bad)await run(tool,v);await run(tool,{...args,extra:1});for(const key of Object.keys(args)){const omit={...args};delete omit[key];await run(tool,omit);for(const v of bad)await run(tool,{...args,[key]:v});}for(const status of [{connected:false},{capabilities:[]},{operations:[]}])await run(tool,args,{status});await run(tool,args,{fail:'request failed: no snapshot'});}
for(const tool of ['live_project_snapshot_export','als_read','als_diff','live_project_snapshot_diff'])for(const key of ['limit','cursor','profile','includeNotes','maxRecords'])for(const value of bad.concat([200,201,12000,12001,'strict','local','invalid']))await run(tool,{...valid[tool],[key]:value});
const root=mkdtempSync(join(tmpdir(),'host-project-oracle-'));const xml=JSON.parse(readFileSync(new URL('./als_oracle.json',import.meta.url))).cases.find(c=>c.label==='full').xml;const path=join(root,'Test.als');writeFileSync(path,gzipSync(xml));const offline=[];const host=new McpHost();
for(const tool of ['als_read','als_lint'])for(const extra of [{},{profile:'strict',includeNotes:true},{profile:'local',limit:1},{profile:'invalid'},{maxRecords:1}]){const args={path,allowedRoot:root,...extra};let out=parse(await host[methods[tool]](1,args));offline.push({tool,extra,result:out});}
const before=parse(host.alsRead(1,{path,allowedRoot:root})).result.content[0].text.page;const changed=join(root,'Changed.als');writeFileSync(changed,gzipSync(xml.replace('Drums','Changed')));for(const args of [{before:{als:{path,allowedRoot:root}},after:{als:{path:changed,allowedRoot:root}}},{before:{pages:[before]},after:{als:{path:changed,allowedRoot:root}}},{before:{als:{path,allowedRoot:root,profile:'strict'}},after:{als:{path:changed,allowedRoot:root}}},{before:{als:{path,allowedRoot:root}},after:{als:{path:changed,allowedRoot:root,profile:'strict'}}}]){offline.push({tool:'als_diff',args,result:parse(host.alsDiff(1,args))});}
// Source-file hashes and artifact IDs stay exact: gzip bytes are saved to avoid gzip header/platform differences.
const raw=readFileSync(path).toString('base64');const changedRaw=readFileSync(changed).toString('base64');
function normalize(v){if(typeof v==='string')return v.replaceAll(root,'ROOT');if(Array.isArray(v))return v.map(normalize);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,v])=>[k,normalize(v)]));return v;}
const backupTraces=[];
for(const mode of ['success','uncertain','expired','wrong-kind','path-changed']){
 const dir=realpathSync(mkdtempSync(join(tmpdir(),'host-backup-oracle-'))),path=join(dir,'Test.als');writeFileSync(path,Buffer.from(raw,'base64'));
 const sim=new DeterministicLiveSimulator(),status=sim.status();status.operations=[...LIVE_REGISTRY_OPERATIONS];sim.status=()=>status;const snapshotAsync=sim.snapshotAsync.bind(sim);let currentPath=path;const calls=[];sim.snapshotAsync=async(c,r)=>{calls.push({context:c??null,request:r??null});const s=await snapshotAsync(c,r);s.set.filePath=currentPath;return s;};const host=new McpHost(sim);const results=[];
 const preview=parse(await host.liveProjectBackupPreviewAsync(1,{confirmation:'backup',allowedRoot:mode==='uncertain'?'relative':dir}));results.push(preview);const id=preview.result.content[0].text.transactionId;const args={transactionId:id,confirmation:'apply',idempotencyKey:'backup-key'};
 if(mode==='expired')host.clipLifecycleTransactions.get(id).expiresAt=0;
 if(mode==='wrong-kind')host.clipLifecycleTransactions.get(id).kind='other';
 if(mode==='path-changed')currentPath=join(dir,'other.als');
 if(mode==='success'){const controller=new AbortController();controller.abort();results.push(await host.liveProjectBackupApplyAsync(1,args,controller.signal));}
 results.push(parse(await host.liveProjectBackupApplyAsync(1,args)));
 results.push(parse(await host.liveProjectBackupApplyAsync(1,args)));
 results.push(parse(await host.liveProjectBackupApplyAsync(1,{...args,idempotencyKey:'other-key'})));
 function norm(v,key=''){if(key==='expiresAt'||key==='mtimeMs')return 0;if(typeof v==='string')return v.replaceAll(dir,'ROOT').replaceAll(id,'backup_ID').replace(/ROOT\/Test\.backup-[^/]+\.als/g,'ROOT/BACKUP.als');if(Array.isArray(v))return v.map(x=>norm(x));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,v])=>[k,norm(v,k)]));return v;}
 backupTraces.push({mode,results:norm(results),calls});rmSync(dir,{recursive:true,force:true});
}
rmSync(root,{recursive:true,force:true});writeFileSync(new URL('./host_project_oracle.json',import.meta.url),JSON.stringify({cases,xml,raw,changedRaw,offline:normalize(offline),backupTraces})+'\n');console.log({cases:cases.length,offline:offline.length});
