import {DeterministicLiveSimulator} from '../../../../apps/mcp-server/dist/src/live.js';
import {createSemanticProjectSnapshot,canonicalSemanticJson} from '../../../../apps/mcp-server/dist/src/project-semantic.js';
import {diffSemanticProjectSnapshots,pageSemanticProjectDiff} from '../../../../apps/mcp-server/dist/src/project-semantic-diff.js';
import {writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const result=fn=>{try{return {ok:fn()??null}}catch(e){return {error:e.message}}};const clone=structuredClone;
const options={profile:'collaboration',exporterVersion:'test',live:{protocol:'ableton-live/v1',adapter:'simulator',provenance:'simulator'}};
const snapshot=()=>new DeterministicLiveSimulator().snapshot();const artifact=(s,o={})=>createSemanticProjectSnapshot(s,{...options,...o});
const makeTrack=(s,index,name)=>({...clone(s.tracks[0]),ref:'track:'+index,objectIdentity:'identity:'+index,name,clips:[],clipSlots:[],devices:[]});
const cases=[];function add(label,before,after,beforeOptions={},afterOptions={}){const a=artifact(before,beforeOptions),b=artifact(after,afterOptions);cases.push({label,before:a,after:b,result:result(()=>diffSemanticProjectSnapshots(a,b))});}
add('unchanged',snapshot(),snapshot());
{const b=snapshot(),a=clone(b);a.set.tempo=128;a.set.name='Renamed Set';add('set change',b,a);}
{const b=snapshot();b.tracks=[makeTrack(b,1,'Drums'),makeTrack(b,2,'Bass')];b.tracks[1].kind='audio';const a=clone(b);a.tracks.reverse();a.tracks[1].name='Percussion';add('unique reorder rename',b,a);}
{const b=snapshot();b.tracks=[makeTrack(b,1,'Duplicate'),makeTrack(b,2,'Duplicate')];b.tracks[1].kind='audio';const a=clone(b);a.tracks.reverse();add('duplicate distinct',b,a);b.tracks[1].kind=b.tracks[0].kind;a.tracks=clone(b.tracks).reverse();add('duplicate ambiguous',b,a);}
const plugin={ref:'device:plugin',name:'Synth',kind:'plugin',className:'VstPluginDevice',parameters:[{ref:'parameter:one',name:'Cutoff',value:0.5,min:0,max:1,automatable:true}],plugin:{presets:['Init'],selectedPresetIndex:0}};
{const b=snapshot();b.tracks[0].devices=[clone(plugin)];for(const variant of ['parameter','preset','replace','rename']){const a=clone(b);if(variant==='parameter')a.tracks[0].devices[0].parameters[0].value=0.75;if(variant==='preset')a.tracks[0].devices[0].plugin.selectedPresetIndex=1;if(variant==='replace'){a.tracks[0].devices[0].name='Other Synth';a.tracks[0].devices[0].className='AuPluginDevice';}if(variant==='rename')a.tracks[0].devices[0].name='Other Synth';add('plugin '+variant,b,a);}}
{const b=snapshot(),a=clone(b);a.tracks.pop();for(const x of [1,3,5,12000])for(const y of [1,3,5,12000])add('incomplete '+x+' '+y,b,a,{maxRecords:x},{maxRecords:y});}
{const b=snapshot();add('privacy mismatch',b,b,{profile:'strict'},{profile:'local'});}
{const b=snapshot(),clip=clone(b.tracks[0].clips[0]);b.tracks=[makeTrack(b,1,'Track A'),makeTrack(b,2,'Track B')];b.arrangementClips=[{trackRef:b.tracks[0].ref,clip}];const a=clone(b);a.arrangementClips[0].trackRef=a.tracks[1].ref;add('clip moved',b,a);}
{const b=snapshot();b.tracks=Array.from({length:10},(_,i)=>({...makeTrack(b,i,'Before '+i),devices:[{ref:'device:'+i,name:'Device '+i,kind:'device',className:'UniqueClass'+i,parameters:[]}]}));const a=clone(b);a.tracks.forEach((t,i)=>t.name='After '+i);add('many changes',b,a);}
{const b=snapshot();const a=clone(b);a.tracks[0].clips[0].notes.reverse();add('note order invariant',b,a);a.tracks[0].clips[0].notes[0].velocity=42;add('note changed',b,a);}
{const b=snapshot();const child={ref:'device:child',name:'Child',kind:'audio-effect',className:'Utility',parameters:[]};b.tracks[0].devices=[{name:'Rack',kind:'rack',parameters:[],chains:[0,1].map(i=>({index:i,name:'Chain '+i,devices:i===0?[clone(child)]:[]}))}];const a=clone(b);a.tracks[0].devices[0].chains[0].devices=[];a.tracks[0].devices[0].chains[1].devices=[child];add('chain moved',b,a);}
{const b=snapshot();const evidence={manifest:{path:'/tmp/Set.als',size:100,mtimeMs:0,sha256:'a'.repeat(64),tracks:1,scenes:1,mediaRefs:1},ableton:{},references:[{value:'/tmp/sample.wav',resolvedPath:'/tmp/sample.wav',resolution:'absolute',exists:true}],referenceBounds:{observed:1,observedKind:'exact',included:1,omitted:0,complete:true}};const changed=clone(evidence);changed.references[0].exists=false;add('dependency missing',b,b,{sourceEvidence:evidence},{sourceEvidence:changed});}
const full=cases.find(c=>c.label==='many changes').result.ok;const ambiguous=cases.find(c=>c.label==='duplicate ambiguous').result.ok;
const paging=[];for(const limit of [1,3,100,200,0,201,1.5]){let cursor;const pages=[];const out=result(()=>{do{const p=pageSemanticProjectDiff(full,{limit,cursor});pages.push(p);cursor=p.page.nextCursor;}while(cursor);return pages;});paging.push({limit,result:out});}
const first=pageSemanticProjectDiff(full,{limit:3});const cursors=['','invalid','e30','bnVsbA','W10',first.page.nextCursor,first.page.nextCursor+'!'];const cursorCases=cursors.map(cursor=>({cursor,result:result(()=>pageSemanticProjectDiff(full,{limit:3,cursor}))}));
const mutations=[];function mutate(label,path,value,remove=false,base=full){const diff=clone(base);let target=diff;for(const key of path.slice(0,-1))target=target[key];if(remove)delete target[path.at(-1)];else target[path.at(-1)]=value;mutations.push({label,diff,result:result(()=>pageSemanticProjectDiff(diff,{limit:3}))});}
for(const key of Object.keys(full)){mutate('omit '+key,[key],null,true);mutate('null '+key,[key],null);}for(const field of Object.keys(full.diff))for(const value of ['',null,12,'sha256:'+'a'.repeat(64)])mutate('identity '+field,['diff',field],value);
for(const field of Object.keys(full.summary))for(const value of [null,false,0,-1,[],{}])mutate('summary '+field,['summary',field],value);
for(const field of Object.keys(full.items[0]))for(const value of [null,false,0,-1,[],{},'unknown'])mutate('change '+field,['items',0,field],value);
const ai=ambiguous.items.findIndex(i=>i.type==='ambiguity');for(const field of Object.keys(ambiguous.items[ai]))for(const value of [null,false,0,-1,[],{},'unknown'])mutate('ambiguity '+field,['items',ai,field],value,false,ambiguous);
for(const [key,value] of [['path','/Users/private'],['before','/Users/private'],['after','Bearer abcdefgh'],['after',{accessToken:'secret'}]])mutate('audit '+key+' '+JSON.stringify(value),['items',0,'details',0,key],value);
const big=snapshot();big.tracks=Array.from({length:11995},(_,i)=>makeTrack(big,i,'Duplicate'));const a=artifact(big);const large={count:11995,artifact:a.artifact,result:diffSemanticProjectSnapshots(a,a)};
writeFileSync(new URL('./project_semantic_diff_oracle.json',import.meta.url),JSON.stringify({cases,paging,cursors:cursorCases,mutations,large})+'\n');console.log({cases:cases.length,mutations:mutations.length,paging:paging.length,cursors:cursorCases.length});
