// Differential evidence from the unchanged TypeScript implementation.
import {DeterministicLiveSimulator} from '../../../../apps/mcp-server/dist/src/live.js';
import {createSemanticProjectSnapshot,validateSemanticProjectArtifact,pageSemanticProjectSnapshot,assembleSemanticProjectPages,semanticCursorArtifactId} from '../../../../apps/mcp-server/dist/src/project-semantic.js';
import {parseAlsXml,modelFromAlsXml,createOfflineAlsArtifact} from '../../../../apps/mcp-server/dist/src/als.js';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {canonicalSemanticJson} from '../../../../apps/mcp-server/dist/src/project-semantic.js';
const clone=structuredClone;const result=fn=>{try{return {ok:fn()??null}}catch(e){return {error:e.message}}};
const opts={exporterVersion:'test',live:{protocol:'ableton-live/v1',adapter:'simulator',provenance:'simulator',registryHash:'a'.repeat(64)}};
const baseline=new DeterministicLiveSimulator().snapshot();const cases=[];
const add=(label,change=()=>{},options={})=>{const snapshot=clone(baseline);change(snapshot);const o={...clone(opts),...options};cases.push({label,snapshot,options:o,result:result(()=>createSemanticProjectSnapshot(snapshot,o))});};
for(const profile of ['collaboration','strict','local','invalid'])add(profile,undefined,{profile});
for(const maxRecords of [0,1,1.2,5,25,12000,13000])add('limit '+maxRecords,undefined,{maxRecords});
add('unset scenes',s=>s.scenes.forEach(c=>Object.assign(c,{tempo:-1,signatureNumerator:-1,signatureDenominator:-1})));
add('set scene',s=>Object.assign(s.scenes[0],{tempo:97,signatureNumerator:7,signatureDenominator:8,tempoEnabled:true}));
add('ref changes',s=>{s.set.ref='99:set:changed';s.tracks[0].ref='99:track:changed';s.tracks[0].clips[0].ref='99:clip:changed';s.tracks[0].clipSlots[0].parentRef=s.tracks[0].ref;s.tracks[0].clipSlots[0].clipRef=s.tracks[0].clips[0].ref;s.tracks[0].clips[0].notes[0].id=999;});
for(const profile of ['collaboration','strict','local'])add('privacy '+profile,s=>{s.set.name='/Users/private/Set';s.tracks[0].name='Bearer abcdefgh';s.tracks[0].devices[0].name='track:secret';s.tracks[0].devices[0].className='C:\\private';s.tracks[0].clips[0].name='e\u0301';s.tracks[0].clips[0].filePath='smb://secret/file.wav';},{profile});
add('audio',s=>{const c=s.tracks[0].clips[0];Object.assign(c,{kind:'audio',gain:0.4,pitchCoarse:2,pitchFine:-11,warpMode:4,warping:true,sampleLength:48000,filePath:'/tmp/Project/Samples/Beat.wav',envelopes:{one:[{time:0,value:1},{time:2,value:0.5,curve:0.1}]},automation:[{time:3,value:0.5}]});});
add('rack and plugin',s=>{s.tracks[0].devices.push({name:'Synth',kind:'plugin',className:'PluginDevice',parameters:[],plugin:{presets:[],selectedPresetIndex:-1}},{name:'Rack',kind:'rack',className:'DrumGroupDevice',parameters:[],variationCount:0,selectedVariationIndex:-1,chains:[{index:0,name:'Kick',devices:[{name:'Max',kind:'device',className:'MaxDevice',parameters:[],maxDevice:{audioIns:[],audioOuts:[1],midiIns:[],midiOuts:[]}}]}],drumPads:[{index:0,name:'Pad',note:36,chains:[{index:1,name:'Snare',devices:[{name:'EQ',kind:'audio-effect',parameters:[],eq8:{globalMode:2}}]}]}]});});
add('all specialized',s=>Object.assign(s.tracks[0].devices[0],{drift:{pitchBendRange:12,modSources:[1,2],modTargets:[1]},eq8:{selectedBand:2},hybridReverb:{irCategory:2,irFile:1,size:0.2},meld:{engine:1,polyphony:8},drumCell:{gain:0.4},looper:{state:1,tempo:120},maxDevice:{audioIns:[],audioOuts:[],midiIns:[],midiOuts:[]}}));
add('depth bound',s=>{let root={name:'root',kind:'rack',parameters:[],chains:[]};let d=root;for(let i=0;i<11;i++){const next={name:'nested'+i,kind:'rack',parameters:[],chains:[]};d.chains=[{index:0,name:'chain',devices:[next]}];d=next;}s.tracks[0].devices=[root];});
const evidence={manifest:{path:'/tmp/Project/Set.als',size:100,mtimeMs:0,sha256:'b'.repeat(64),tracks:200,scenes:150,mediaRefs:4},ableton:{creator:'Ableton Live 12',majorVersion:'5',minorVersion:'12.4',schemaChangeCount:'3'},references:[{value:'/tmp/Project/Samples/Kick.wav',resolvedPath:'/tmp/Project/Samples/Kick.wav',resolution:'absolute',projectLocal:true,exists:false},{value:'/Library/Packs/Piano/Note.wav',resolvedPath:'/Library/Packs/Piano/Note.wav',resolution:'absolute',exists:true},{value:'smb://secret/a.wav',resolution:'network'},{value:'Samples/unknown.wav',resolution:'unresolved'}],referenceBounds:{observed:5,observedKind:'lower-bound',included:4,omitted:1,complete:false}};
for(const profile of ['strict','collaboration','local'])add('source '+profile,undefined,{sourceEvidence:evidence,projectPath:'/tmp/Project/Set.als',profile,live:{...opts.live,version:'Live 12'}});
add('source privacy',undefined,{sourceEvidence:{...evidence,ableton:{creator:'file:///private',majorVersion:'track:abc',minorVersion:'é',schemaChangeCount:'Bearer abcdefgh'}},live:{...opts.live,version:'/private/live'}});
const mutations=[];const base=cases[0].result.ok;
function setPath(obj,path,value,remove=false){let target=obj;for(const key of path.slice(0,-1))target=target[key];if(remove)delete target[path.at(-1)];else target[path.at(-1)]=value;}
function mutate(label,path,value,remove=false){const artifact=clone(base);setPath(artifact,path,value,remove);mutations.push({label,path,value:value??null,remove,result:result(()=>validateSemanticProjectArtifact(artifact))});}
for(const key of Object.keys(base)){mutate('omit '+key,[key],null,true);mutate('null '+key,[key],null);}mutate('extra',['unexpected'],1);
for(const [kind,record] of Object.entries(Object.fromEntries(base.records.map((r,i)=>[r.kind,i])))){const row=base.records[record];for(const key of Object.keys(row.data)){mutate(`${kind} omit ${key}`,['records',record,'data',key],null,true);for(const value of [null,true,'invalid',-1,{},[]])mutate(`${kind} ${key} ${JSON.stringify(value)}`,['records',record,'data',key],value);}for(const key of Object.keys(row.matching))mutate(`${kind} matching ${key}`,['records',record,'matching',key],'bad');mutate(`${kind} unknown`,['records',record,'data','unknown'],1);mutate(`${kind} authority`,['records',record,'data','token'],'secret');}
for(const field of ['id','semanticHash','exporterVersion'])for(const value of ['',null,{},'x'])mutate('identity '+field,['artifact',field],value);
for(const field of ['protocol','adapter','provenance','registryHash','version'])for(const value of ['',null,{},'x'])mutate('provenance '+field,['provenance','live',field],value);
for(const section of Object.keys(base.manifest))for(const field of Object.keys(base.manifest[section]))mutate('manifest '+section+'.'+field,['manifest',section,field],field==='complete'?false:0);
const pages=[];for(const limit of [1,5,100,200,0,201,1.5]){let cursor;const emitted=[];let out=result(()=>{do{const page=pageSemanticProjectSnapshot(base,{limit,cursor});emitted.push(page);cursor=page.page.nextCursor;}while(cursor);return emitted;});pages.push({limit,result:out});}
const pageMutations=[];const bundle=pages.find(p=>p.limit===5).result.ok;
const pageChange=(label,fn)=>{const copy=clone(bundle);fn(copy);pageMutations.push({label,pages:copy,result:result(()=>assembleSemanticProjectPages(copy))});};
pageChange('reorder',p=>p.reverse());pageChange('overlap',p=>p[1]=p[0]);pageChange('incomplete',p=>p.pop());pageChange('cursor',p=>p[0].page.nextCursor='invalid');pageChange('extra',p=>p[0].extra=1);pageChange('header',p=>p[1].artifact.exporterVersion='other');pageChange('returned',p=>p[0].page.returned=3);pageChange('negative',p=>p[0].page.offset=-1);pageChange('coordinates',p=>p[0].page.offset=null);pageChange('empty',p=>p.length=0);
const cursors=['','invalid','e30','bnVsbA','W10',bundle[0].page.nextCursor,bundle[0].page.nextCursor+'!'];const cursorCases=cursors.map(cursor=>({cursor,id:semanticCursorArtifactId(cursor)??null,result:result(()=>pageSemanticProjectSnapshot(base,{cursor,limit:5}))}));
const als=JSON.parse(readFileSync(new URL('./als_oracle.json',import.meta.url),'utf8'));const offline=[];for(const row of als.cases.filter(c=>['full','audio','timing Time="8" Length="-1"'].includes(c.label)))for(const profile of ['strict','collaboration','local']){const model=modelFromAlsXml(parseAlsXml(row.xml),'Offline');const source={path:'/tmp/Offline.als',raw:Buffer.from('fixture'),xml:row.xml,size:7,mtimeMs:0,sha256:'c'.repeat(64)};const options={profile,exporterVersion:'test'};offline.push({xml:row.xml,options,result:result(()=>createOfflineAlsArtifact(source,model,options))});}
const rehashed=[];
const hash=v=>'sha256:'+createHash('sha256').update(canonicalSemanticJson(v)).digest('hex');
function rehash(v){for(const r of v.records){r.contentFingerprint=hash({kind:r.kind,name:r.name??null,data:r.data});r.semanticFingerprint=hash(r.matching);r.nameFingerprint=hash([r.kind,r.name??null]);}for(const section of Object.keys(v.manifest))v.manifest[section].digest=hash(v.records.filter(r=>r.section===section));v.artifact.semanticHash=hash({schema:v.schema,policy:v.policy,set:v.set,manifest:v.manifest,safety:v.safety,records:v.records});v.artifact.id=hash({schema:v.schema,exporterVersion:v.artifact.exporterVersion,semanticHash:v.artifact.semanticHash,policy:v.policy,provenance:v.provenance,set:v.set,manifest:v.manifest,safety:v.safety,records:v.records});}
for(const row of mutations.filter(r=>r.label.includes('authority')||r.label.includes('clipCount')||r.label.includes('armed')||r.label.includes('complete')||r.label.includes('unknown'))){const artifact=clone(base);setPath(artifact,row.path,row.value,row.remove);const rehashResult=result(()=>rehash(artifact));if('error' in rehashResult)continue;rehashed.push({label:row.label,artifact,result:result(()=>validateSemanticProjectArtifact(artifact))});}
for(const value of ['99:track:LIVE-REF','42:clip_slot:0:0','Bearer abcdefgh','/Users/private','x /Users/private','Verse / Chorus']){const artifact=clone(base);artifact.records.find(r=>r.kind==='unavailable').data.reason=value;rehash(artifact);rehashed.push({label:value,artifact,result:result(()=>validateSemanticProjectArtifact(artifact))});}
const large=[];for(const [count,maxRecords,limit,long] of [[500,120,17,false],[2056,12000,1,false],[250,12000,200,true]]){const snapshot=clone(baseline);snapshot.tracks=Array.from({length:count},(_,i)=>({...clone(baseline.tracks[0]),ref:'track:large-'+i,name:'Track '+i+(long?'x'.repeat(500):''),clips:[],clipSlots:[],devices:[],...(long?{routing:{inputType:'a'.repeat(512),inputSubRouting:'b'.repeat(512),outputType:'c'.repeat(512),outputSubRouting:'d'.repeat(512)}}:{})}));const options={...opts,maxRecords};const artifact=createSemanticProjectSnapshot(snapshot,options);const first=result(()=>pageSemanticProjectSnapshot(artifact,{limit}));large.push({count,maxRecords,limit,long,identity:artifact.artifact,manifest:artifact.manifest,first});}
writeFileSync(new URL('./project_semantic_oracle.json',import.meta.url),JSON.stringify({cases,mutations,pages,pageMutations,cursors:cursorCases,offline,rehashed,large})+'\n');
console.log({cases:cases.length,mutations:mutations.length,pages:pages.length,pageMutations:pageMutations.length,cursors:cursorCases.length,offline:offline.length});
